- name: Metabase
  matchers:
    - part: title
      type: word
      words:
        - Metabase

- name: Trino
  vendor: Trino Software Foundation
  matchers:
    - part: title
      type: word
      words:
        - "Cluster Overview - Trino"
- name: eXist-DB
  vendor: exist-db
  matchers:
    - part: title
      type: word
      words:
        - "eXist db"