- name: Metabase
  matchers:
    - part: title
      type: word
      words:
        - Metabase
- name: prisma
  vendor: prisma
  matchers:
    - part: body
      type: word
      condition: and
      words:
        - "generator"
        - "datasource "
        - "provider ="
        - "model "

- name: Dgraph
  vendor: dgraph
  matchers:
    - part: title
      type: word
      words:
        - Dgraph
- name: eXist-DB
  vendor: exist-db
  matchers:
    - part: title
      type: word
      words:
        - "eXist db"