- name: Metabase
  matchers:
    - part: title
      type: word
      words:
        - Metabase
- name: Milvus
  vendor: milvus
  matchers-condition: and
  matchers:
    - part: body
      type: word
      condition: or
      words:
        - "the expr auth is invalid"
        - "Milvus"
    - part: body
      type: word
      words:
        - "404 page not found"
- name: eXist-DB
  vendor: exist-db
  matchers:
    - part: title
      type: word
      words:
        - "eXist db"